In [1]:
sentences = ['যদি তোর ডাক শুনে কেউ না আসে, তবে একলা চলো রে','শিমুল কাঠই হোক বা বকুল কাঠই হোক, আগুনের চেহারাটা একই']

In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/cavid/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
# make transform 
vectorizer = CountVectorizer()

In [5]:
vectorizer.fit(sentences)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [6]:
vectorizer.vocabulary_

{'যদ': 8,
 'আস': 1,
 'তব': 6,
 'একল': 3,
 'চল': 4,
 'ঠই': 5,
 'বক': 7,
 'আগ': 0,
 'একই': 2}

In [7]:
import warnings 
warnings.filterwarnings("ignore")

In [8]:
from nltk import word_tokenize
vectorizer = CountVectorizer(encoding = 'utf-8', tokenizer = word_tokenize)
vectorizer.fit(sentences)
vectorizer.vocabulary_

{'যদি': 15,
 'তোর': 11,
 'ডাক': 9,
 'শুনে': 18,
 'কেউ': 6,
 'না': 12,
 'আসে': 2,
 ',': 0,
 'তবে': 10,
 'একলা': 4,
 'চলো': 7,
 'রে': 16,
 'শিমুল': 17,
 'কাঠই': 5,
 'হোক': 19,
 'বা': 14,
 'বকুল': 13,
 'আগুনের': 1,
 'চেহারাটা': 8,
 'একই': 3}

In [9]:
print(vectorizer.vocabulary_)

{'যদি': 15, 'তোর': 11, 'ডাক': 9, 'শুনে': 18, 'কেউ': 6, 'না': 12, 'আসে': 2, ',': 0, 'তবে': 10, 'একলা': 4, 'চলো': 7, 'রে': 16, 'শিমুল': 17, 'কাঠই': 5, 'হোক': 19, 'বা': 14, 'বকুল': 13, 'আগুনের': 1, 'চেহারাটা': 8, 'একই': 3}


In [10]:
vectorizer.transform(sentences).toarray()

array([[1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2]])

In [11]:
vec = CountVectorizer()
x = vec.fit_transform(sentences).toarray()


In [12]:
print(x.shape)

(2, 9)


In [13]:
print(vec.get_feature_names())

['আগ', 'আস', 'একই', 'একল', 'চল', 'ঠই', 'তব', 'বক', 'যদ']


In [14]:
vectorizer = CountVectorizer(encoding='utf-8', token_pattern=r'[\u0980-\u09ff]+')

In [15]:
vectorizer.fit(sentences)
vectorizer.vocabulary_

{'যদি': 14,
 'তোর': 10,
 'ডাক': 8,
 'শুনে': 17,
 'কেউ': 5,
 'না': 11,
 'আসে': 1,
 'তবে': 9,
 'একলা': 3,
 'চলো': 6,
 'রে': 15,
 'শিমুল': 16,
 'কাঠই': 4,
 'হোক': 18,
 'বা': 13,
 'বকুল': 12,
 'আগুনের': 0,
 'চেহারাটা': 7,
 'একই': 2}

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer =TfidfVectorizer(encoding='utf-8', tokenizer=word_tokenize)

vectorizer.fit(sentences)
vectorizer.vocabulary_

{'যদি': 15,
 'তোর': 11,
 'ডাক': 9,
 'শুনে': 18,
 'কেউ': 6,
 'না': 12,
 'আসে': 2,
 ',': 0,
 'তবে': 10,
 'একলা': 4,
 'চলো': 7,
 'রে': 16,
 'শিমুল': 17,
 'কাঠই': 5,
 'হোক': 19,
 'বা': 14,
 'বকুল': 13,
 'আগুনের': 1,
 'চেহারাটা': 8,
 'একই': 3}

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(encoding = 'utf-8', tokenizer= word_tokenize)
vectorizer.fit(sentences)
vectorizer.vocabulary_

{'যদি': 15,
 'তোর': 11,
 'ডাক': 9,
 'শুনে': 18,
 'কেউ': 6,
 'না': 12,
 'আসে': 2,
 ',': 0,
 'তবে': 10,
 'একলা': 4,
 'চলো': 7,
 'রে': 16,
 'শিমুল': 17,
 'কাঠই': 5,
 'হোক': 19,
 'বা': 14,
 'বকুল': 13,
 'আগুনের': 1,
 'চেহারাটা': 8,
 'একই': 3}

In [18]:
vectorizer.transform(sentences).toarray()

array([[0.2097554 , 0.        , 0.29480389, 0.        , 0.29480389,
        0.        , 0.29480389, 0.29480389, 0.        , 0.29480389,
        0.29480389, 0.29480389, 0.29480389, 0.        , 0.        ,
        0.29480389, 0.29480389, 0.        , 0.29480389, 0.        ],
       [0.186811  , 0.26255634, 0.        , 0.26255634, 0.        ,
        0.52511268, 0.        , 0.        , 0.26255634, 0.        ,
        0.        , 0.        , 0.        , 0.26255634, 0.26255634,
        0.        , 0.        , 0.26255634, 0.        , 0.52511268]])

In [19]:
sentences

['যদি তোর ডাক শুনে কেউ না আসে, তবে একলা চলো রে',
 'শিমুল কাঠই হোক বা বকুল কাঠই হোক, আগুনের চেহারাটা একই']

In [20]:
cities = ['ঢাকা', 'বার্লিন', 'কুমিল্লা', 'শিকাগো', 'সিঙ্গাপুর']

In [21]:
cities

['ঢাকা', 'বার্লিন', 'কুমিল্লা', 'শিকাগো', 'সিঙ্গাপুর']

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
encoder = LabelEncoder()

In [24]:
city_labels = encoder.fit_transform(cities)

In [25]:
city_labels

array([1, 2, 0, 3, 4])

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
encoder = OneHotEncoder(sparse=False)
city_labels = city_labels.reshape((5,1))
encoder.fit_transform(city_labels)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
city_labels

array([[1],
       [2],
       [0],
       [3],
       [4]])